### ISSUE TITLE
Tests fail in development environment

### ISSUE THREAD

**Issue by svenmueller** [sphereio/node-s3-utils#24]
```bash
Failures:

  1) S3Client :: resizeCompressAndUploadImages should call compress function
   Message:
     Expected spy compressImage to have been called.
   Stacktrace:
     Error: Expected spy compressImage to have been called.
    at /Users/smueller/dev/src/node-s3-utils/test/services/s3client.spec.js:196:47
    at tryCatch1 (/Users/smueller/dev/src/node-s3-utils/node_modules/bluebird/js/main/util.js:43:21)
    at Promise$_callHandler [as _callHandler] (/Users/smueller/dev/src/node-s3-utils/node_modules/bluebird/js/main/promise.js:649:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/Users/smueller/dev/src/node-s3-utils/node_modules/bluebird/js/main/promise.js:663:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/Users/smueller/dev/src/node-s3-utils/node_modules/bluebird/js/main/promise.js:826:14)
    at Promise$_settlePromises [as _settlePromises] (/Users/smueller/dev/src/node-s3-utils/node_modules/bluebird/js/main/promise.js:969:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/Users/smueller/dev/src/node-s3-utils/node_modules/bluebird/js/main/async.js:75:12)
    at Async$consumeFunctionBuffer (/Users/smueller/dev/src/node-s3-utils/node_modules/bluebird/js/main/async.js:38:14)

  2) S3Client :: resizeCompressAndUploadImages should call put function with cache-control header
   Message:
     Expected spy putFile to have been called with [ '/Users/smueller/dev/src/node-s3-utils/test/services/../../examples/foo_thumbnailjpg', 'products/foo_thumbnailjpg', { x-amz-acl : 'public-read', Cache-Control : 'max-age=42' } ] but it was never called.
   Stacktrace:
     Error: Expected spy putFile to have been called with [ '/Users/smueller/dev/src/node-s3-utils/test/services/../../examples/foo_thumbnailjpg', 'products/foo_thumbnailjpg', { x-amz-acl : 'public-read', Cache-Control : 'max-age=42' } ] but it was never called.
    at /Users/smueller/dev/src/node-s3-utils/test/services/s3client.spec.js:226:49
    at tryCatch1 (/Users/smueller/dev/src/node-s3-utils/node_modules/bluebird/js/main/util.js:43:21)
    at Promise$_callHandler [as _callHandler] (/Users/smueller/dev/src/node-s3-utils/node_modules/bluebird/js/main/promise.js:649:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/Users/smueller/dev/src/node-s3-utils/node_modules/bluebird/js/main/promise.js:663:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/Users/smueller/dev/src/node-s3-utils/node_modules/bluebird/js/main/promise.js:826:14)
    at Promise$_settlePromises [as _settlePromises] (/Users/smueller/dev/src/node-s3-utils/node_modules/bluebird/js/main/promise.js:969:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/Users/smueller/dev/src/node-s3-utils/node_modules/bluebird/js/main/async.js:75:12)
    at Async$consumeFunctionBuffer (/Users/smueller/dev/src/node-s3-utils/node_modules/bluebird/js/main/async.js:38:14)

Finished in 9.492 seconds
34 tests, 61 assertions, 2 failures, 0 skipped
```

**Comment by svenmueller** [comment]
Library image magic was missing:
```bash
brew install imagemagick
```
